version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: org.springframework.boot:spring-boot-starter-parent
    versions:
    - 2.4.2
    - 2.4.3
    - 2.4.4
  - dependency-name: org.springframework.cloud:spring-cloud-function-adapter-aws
    versions:
    - 3.1.1
  - dependency-name: com.amazonaws:aws-lambda-java-events
    versions:
    - 3.7.0
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: serverless
    versions:
    - 2.21.1
    - 2.22.0
    - 2.23.0
    - 2.25.1
    - 2.25.2
    - 2.27.0
    - 2.27.1
    - 2.28.0
    - 2.28.4
    - 2.28.6
    - 2.28.7
    - 2.29.0
    - 2.30.0
    - 2.30.3
    - 2.31.0
    - 2.32.0
    - 2.32.1
    - 2.33.1
    - 2.34.0
    - 2.35.0
    - 2.36.0
    - 2.37.2
  - dependency-name: serverless-prune-plugin
    versions:
    - 1.4.4
